const mockData = [
  {
    id: "1",
    bagtag: 349239,
    source: "EWR",
    longitude: 90,
    latitude: 91,
    destination: "LAX",
    currentTask: false,
    completed: false,
  },
  {
    id: "2",
    bagtag: 934343,
    source: "ANC",
    longitude: 92,
    latitude: 93,
    destination: "SEA",
    currentTask: false,
    completed: false,
  },
  {
    id: "3",
    bagtag: 783473,
    source: "EWR",
    longitude: 94,
    latitude: 95,
    destination: "LAX",
    currentTask: false,
    completed: false,
  },
  {
    id: "4",
    bagtag: 123943,
    source: "ORD",
    longitude: 96,
    latitude: 97,
    destination: "SFO",
    currentTask: false,
    completed: false,
  },
  {
    id: "5",
    bagtag: 948202,
    source: "OAK",
    longitude: 98,
    latitude: 100,
    destination: "LAX",
    currentTask: false,
    completed: false,
  },
  {
    id: "6",
    bagtag: 938281,
    source: "MDW",
    longitude: 101,
    latitude: 102,
    destination: "EWR",
    currentTask: false,
    completed: false,
  },
  {
    id: "7",
    bagtag: 3847382,
    source: "BUR",
    longitude: 103,
    latitude: 105,
    destination: "PSP",
    currentTask: false,
    completed: false,
  },
];

export default mockData;
