const mockData = [
  {
    bagId: "1",
    source: "EWR",
    location: "Terminal 3",
    destination: "LAX",
    currentTask: false,
    completed: false,
  },
  {
    bagId: "2",
    source: "ANC",
    location: "Terminal 2",
    destination: "SEA",
    currentTask: false,
    completed: false,
  },
  {
    bagId: "3",
    source: "EWR",
    location: "Baggage Claim",
    destination: "LAX",
    currentTask: false,
    completed: false,
  },
  {
    bagId: "4",
    source: "ORD",
    location: "Terminal 2: Tarmac",
    destination: "SFO",
    currentTask: false,
    completed: false,
  },
  {
    bagId: "5",
    source: "OAK",
    location: "Terminal 1: Lobby",
    destination: "LAX",
    currentTask: false,
    completed: false,
  },
  {
    bagId: "6",
    source: "MDW",
    location: "Terminal 3: MP Lounge",
    destination: "EWR",
    currentTask: false,
    completed: false,
  },
  {
    bagId: "7",
    source: "BUR",
    location: "Terminal 2: Lost and Found",
    destination: "PSP",
    currentTask: false,
    completed: false,
  },
];

export default mockData;
